### ISSUE TITLE
Build failure on stable with non-default features

### ISSUE THREAD

**Issue by neoeinstein** [iliekturtles/uom#234]
FYI, looks like the issue with #224 has arisen on stable. `uom` fails to compile on the latest stable version: 1.49.0, with `default-features = false` and the following options: `["f64", "std", "si", "use_serde"]`. I did confirm that going back to the default feature set and just adding "use_serde" works on 1.49.0, however.

Sample of the error listing: 
```
   ::: /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/uom-0.30.0/src/system.rs:244:20
    |
244 |           pub struct Quantity<D, U, V>
    |                      -------- required by a bound in this
245 |           where
246 |               D: Dimension + ?Sized,
    |                  --------- required by this bound in `si::Quantity`
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider further restricting type parameter `N`
    |
290 |                 V: crate::num_traits::Num + crate::Conversion<V>, N: Integer
    |                                                                 ^^^^^^^^^^^^

error[E0277]: the trait bound `J: Integer` is not satisfied
```

**Comment by iliekturtles** [comment]
Thanks for the report! I can reproduce and will find a fix. I'm planning to release a new version to crates.io once this is fixed.

**Comment by iliekturtles** [comment]
Thanks again for the report. The fix was just published to crates.io in v0.31.0.
