### ISSUE TITLE
Build fails when autoconvert feature is disabled

### ISSUE THREAD

**Issue by dmit** [iliekturtles/uom#141]
The new `impl_from!` macro unconditionally uses `si::change_base`, which is only available when the `autoconvert` feature is enabled. Disabling the feature causes the following build error:
```
error[E0432]: unresolved import `si::change_base`
  --> src\si\mod.rs:93:14
   |
93 |     use si::{change_base, Dimension, Quantity, Units};
   |              ^^^^^^^^^^^ no `change_base` in `si`
```

This is a regression in uom 0.23.0, introduced in #132.
